### ISSUE TITLE
flask-base exited with code 0

### ISSUE THREAD

**Issue by ivorscott** [lazToum/docker_playground#1]
I get a flask-base exited with code 0.

<img width="1395" alt="screen shot 2016-10-08 at 2 21 22 am" src="https://cloud.githubusercontent.com/assets/1488558/19210916/f0f338f2-8cfd-11e6-9afe-8f88675d6c50.png">

Doesn't seem to be working for me.

**Comment by lazToum** [comment]
actualy there was also an issue with the mongoengine connection
https://github.com/MongoEngine/flask-mongoengine/issues/259
for the 0 code : added tty: true on docker-compose.yml
