### ISSUE TITLE
Can't get the application to run

### ISSUE THREAD

**Issue by ivorscott** [lazToum/docker_playground#2]
I feel like I didn't follow the instructions correctly. i did:

I ran ./setup.sh but I cannot see the app when I go to http://localhost

<img width="1202" alt="screen shot 2016-10-08 at 3 56 36 pm" src="https://cloud.githubusercontent.com/assets/1488558/19215572/e6965732-8d6f-11e6-8201-4e6fad0830cc.png">

<img width="1167" alt="screen shot 2016-10-08 at 3 49 22 pm" src="https://cloud.githubusercontent.com/assets/1488558/19215532/f7c08088-8d6e-11e6-85a8-ace32a011823.png">

**Comment by lazToum** [comment]
can you try with the latest docker-compose?
i tried it again, and it works for me.
can you also check the logs?
docker exec -it flask-gunicorn-nginx /bin/bash (they are inside /var/log)

![screenshot from 2016-10-08 22-59-02](https://cloud.githubusercontent.com/assets/4764837/19215619/764fe510-8dab-11e6-9392-3c10724a279a.png)
![screenshot from 2016-10-08 22-58-56](https://cloud.githubusercontent.com/assets/4764837/19215625/805c1470-8dab-11e6-919a-9c6d71b5a46a.png)
![screenshot from 2016-10-08 22-59-17](https://cloud.githubusercontent.com/assets/4764837/19215629/888a6db8-8dab-11e6-8f0f-e8e4b7135c79.png)

**Comment by ivorscott** [comment]
Got it. Something is apparently wrong with my development environment (using Mac). When I ran this in my Ubuntu server in production and it worked. Clearly this setup is for development or staging. I like the side bar details, is this supervisor? (http://supervisord.org/introduction.html) I haven't used that before. Do you have any suggestions on how to remove it when going into production? Thank you.

**Comment by lazToum** [comment]
I'm glad you got it working. Yes, this setup is only for development. Actually the sidebar is from a flask plugin (https://flask-debugtoolbar.readthedocs.io/en/latest/). It's imported in project.py
 `from flask_debugtoolbar import DebugToolbarExtension`
In production it's not needed, so you will have to modify this file (project.py):
remove: 

```
DebugToolbarExtension(app)
app.config['DEBUG_TB_PANELS'] = (
    'flask_debugtoolbar.panels.versions.VersionDebugPanel',
    'flask_debugtoolbar.panels.timer.TimerDebugPanel',
    'flask_debugtoolbar.panels.headers.HeaderDebugPanel',
    'flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel',
    'flask_debugtoolbar.panels.template.TemplateDebugPanel',
    'flask_debugtoolbar.panels.logger.LoggingPanel',
    'flask_mongoengine.panels.MongoDebugPanel'
)
app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False
```

set: 
`app.debug = False`

**Comment by ivorscott** [comment]
Assuming I haven't changed your setup how do I enter mongodb interactively?
I am trying to find the todos statements. In the setup.sh file I see the credentials but I am not sure how to use them.

Something like this I believe, but I find anything. Sorry for my ignorance.
docker exec -it flask-mongo mongo admin

**Comment by lazToum** [comment]
That's right,
`docker exec -it flask-mongo mongo -urootUser -pchangeMe -authenticationDatabase admin flaskDb` for the root user, or 
`docker exec -it flask-mongo mongo -uflaskUser -pchangeMe flaskDb` for the app user.
Or if you have a mongo client, you can donect from the host, as the port is shared between the host and the container, so just 
`mongo -uflaskUser -pchangeMe flaskDb`
(after that it's just `db.todo.find()`)
You can disable the authentication requirement in the mongod.conf file.
I know all that should be on the README.dm file (poor documentation), but i'm even lazy to make TODO (and add it there)

**Comment by ivorscott** [comment]
I deleted my commented because I figured it out, although didn't know about the connection via mongo client. Very nice. Thanks a bunch.
