### ISSUE TITLE
HTTP request took too long to complete

### ISSUE THREAD

**Issue by nicolasfguillaume** [lazToum/docker_playground#5]
Hi,

I just cloned your repo and executed `docker-compose up`. Then I get the following error:
```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60)
```

I tried to increased the timeout (`COMPOSE_HTTP_TIMEOUT=200 docker-compose up`), but I still get the error.

What I am doing wrong? Thanks

**Comment by lazToum** [comment]
Hi, i run the same (from scratch), but i don't get this error. It seems to be working on my machine. 
versions:
docker-compose version 1.20.1
docker version 18.03.0-ce
Do you have more info from "--verbose" ?
